file_search_maxima: ["/home/zaki/maxima_prgs/###.mac","~/cvs/CASEY/maxima/###.mac","C:\\cygwin\\home\\dp2\\cvs\\CASEY\\maxima\\###.mac"];
load("delta");
load("dsimplify");
load("dRewrite");
P : 1/b;
expectations : [ 	expectation(X(I,K)) = Cases( 
								Case(In(Df(Eq(I),Eq(K))),P)),		
			expectation(X(I,K)*X(J,L)) = Cases(	
								Case(In(Df(Eq(K,L),Eq(I,J))), P),
								Case(In(Df(Eq(I,L),Eq(K,J))), P),
								Case(In(Df(Eq(K),Eq(L),Eq(I),Eq(J))), P^2),
								Case(In(Df(Eq(I,J),Eq(K),Eq(L))), P^2),
								Case(In(Df(Eq(I,L),Eq(J),Eq(K))), P^2),
								Case(In(Df(Eq(K,J),Eq(I),Eq(L))), P^2),
								Case(In(Df(Eq(K,L),Eq(I),Eq(J))), P^2)
		)];

makeRVFamily(X, randomHistogram, [P], expectations );
makeRV(X,randomHistogram,[P]);

sumexpand:true;

Z : sum(sum(f(i)*g(j)*X(i,j),i,1,n),j,1,n);

print("Input : ",Z);

res : ex1(Z);
res2 : dRewrite ( dsimplify (res) );
print("Result of ex: ",res2);

res1 : var (Z);
res3 : dRewrite (dsimplify (res1));
print("Result of var: ",res3);


