file_search_maxima: ["~/cvs/CASEY/maxima/###.mac","C:\\cygwin\\home\\dp2\\cvs\\CASEY\\maxima\\###.mac"];
load("delta");
load("dsimplify");
load("dRewrite");
P : 1/b;
expectations : [ 	expectation(X(I,K)) = P,
			expectation(X(I,K)*X(J,L)) = Cases(	
								Case(In(Df(Eq(K,L)), Df(Eq(I,J))), P),
								Case(In(Df(Eq(K,L)), Df(Eq(I),Eq(J))), P^2),
								Case(In(Df(Eq(K),Eq(L)), Df(Eq(I,J))), 0),
								Case(In(Df(Eq(K),Eq(L)), Df(Eq(I),Eq(J))), P^2)),
			expectation(X(I,K)*X(J,K)*X(IP,L)) = Cases(	
							/***K = L ***/
								Case(In(Df(Eq(K,L)), Df(Eq(I,J,IP))), P),
		  						/* symmetric cases */
								SymCase(In(Df(Eq(K,L)), Df(Eq(I,J),Eq(IP))), P^2),
								/*******/
								Case(In(Df(Eq(K,L)), Df(Eq(J),Eq(IP),Eq(I))), P^3),

							/***K # L ***/
								Case(In(Df(Eq(K),Eq(L)), Df(Eq(I,J,IP))), 0),
		  						/* symmetric cases */
								SymCase(In(Df(Eq(K),Eq(L)), Df(Eq(I,IP),Eq(J))), 0),
								/*******/
								Case(In(Df(Eq(K),Eq(L)), Df(Eq(I,J),Eq(IP))), P^2),
								Case(In(Df(Eq(K),Eq(L)), Df(Eq(J),Eq(IP),Eq(I))), P^3)),

			expectation(X(I,K)*X(J,K)*X(IP,L)*X(JP,L)) = Cases(	
							/***K = L ***/
								Case(In(Df(Eq(K,L)), Df(Eq(I,J,IP,JP))), P),
		  						/* symmetric cases */
								SymCase(In(Df(Eq(K,L)), Df(Eq(I,J,IP),Eq(JP))), P^2),
								/*******/
		  						/* symmetric cases */
								SymCase(In(Df(Eq(K,L)), Df(Eq(I,J),Eq(IP,JP))), P^2),
								/*******/
		  						/* symmetric cases */
								SymCase(In(Df(Eq(K,L)), Df(Eq(I,J),Eq(IP),Eq(JP))), P^3),
								/*******/
								Case(In(Df(Eq(K,L)), Df(Eq(J),Eq(IP),Eq(I),Eq(JP))), P^4),

							/***K # L ***/
								Case(In(Df(Eq(K),Eq(L)), Df(Eq(I,J,IP,JP))), 0),
		  						/* symmetric cases */
								SymCase(In(Df(Eq(K),Eq(L)), Df(Eq(I,J,IP),Eq(JP))), 0),
								/*******/
		  						/* otherwise */
								Case(In(Df(Eq(K),Eq(L)), Df(Eq(I,J),Eq(IP,JP))), P^2),
								Case(In(Df(Eq(K),Eq(L)), Df(Eq(I,IP),Eq(J,JP))), 0),
								Case(In(Df(Eq(K),Eq(L)), Df(Eq(I,JP),Eq(J,IP))), 0),
								/*******/
		  						/* otherwisw*/
								Case(In(Df(Eq(K),Eq(L)), Df(Eq(I,J),Eq(IP),Eq(JP))), P^3),
								Case(In(Df(Eq(K),Eq(L)), Df(Eq(I,IP),Eq(J),Eq(JP))), 0),
								Case(In(Df(Eq(K),Eq(L)), Df(Eq(I,JP),Eq(IP),Eq(J))), 0),
								Case(In(Df(Eq(K),Eq(L)), Df(Eq(J,IP),Eq(I),Eq(JP))), 0),
								Case(In(Df(Eq(K),Eq(L)), Df(Eq(J,JP),Eq(I),Eq(IP))), 0),
								Case(In(Df(Eq(K),Eq(L)), Df(Eq(IP,JP),Eq(I),Eq(J))), P^3),
								/*******/
								Case(In(Df(Eq(K),Eq(L)), Df(Eq(J),Eq(IP),Eq(I),Eq(JP))), P^4))];

makeRVFamily(X, randomHistogram, [P], expectations );
makeRV(X,randomHistogram,[P]);

expression  : sum(sum(f(i)*X(i,k),i,1,N)^2,k,1,b);
res1 : dRewrite(dsimplify( ex1 (expression )));
print("Result1 of Ex: ",res1);
res1 : var (expression );
res2 : dsimplify (res1);
res3 : dRewrite (res2);
print("Result of Variance: ",res3);

